import { iLocalization } from '../iLocalization';

const vi: iLocalization = {
  en: 'Tiếng Anh',
  vi: 'Tiếng Việt',
  login: 'Đăng nhập',
  logout: 'Đăng xuất',
  signup: 'Đăng ký',
  // Auth — phone + OTP
  authPhoneTitle: 'Đăng nhập',
  authPhoneSubtitle: 'Nhập số điện thoại của bạn để tiếp tục',
  authPhoneLabel: 'Số điện thoại',
  authPhonePlaceholder: 'Nhập số điện thoại',
  authPhoneInvalid: 'Số điện thoại không hợp lệ',
  authContinue: 'Tiếp tục',
  authOtpTitle: 'Nhập mã xác thực',
  authOtpSubtitle: 'Chúng tôi đã gửi mã 6 số tới {{phone}}',
  authOtpVerify: 'Xác nhận',
  authOtpResend: 'Gửi lại mã',
  authOtpResendCountdown: 'Gửi lại sau {{seconds}}s',
  authOtpInvalid: 'Mã OTP không đúng',
  authOtpDevHint: '(DEV) dùng 000000',
  // Country picker
  countryPickerTitle: 'Chọn quốc gia',
  countryPickerSearch: 'Tìm theo tên hoặc mã',
  countryPickerEmpty: 'Không tìm thấy quốc gia',
  // Home — map & search
  homeWhereTo: 'Bạn muốn đi đâu?',
  homeSavedHome: 'Nhà',
  homeSavedWork: 'Cơ quan',
  homeLocationDenied: 'Vị trí đang tắt. Bật để tìm xe ở gần bạn.',
  homeEnableLocation: 'Bật vị trí',
  // Route summary
  routeFetchError: 'Không lấy được lộ trình',
  routeDistanceLabel: 'Khoảng cách',
  routeDurationLabel: 'Thời gian',
  // Search destination
  searchDestinationTitle: 'Tìm điểm đến',
  searchDestinationPlaceholder: 'Nhập địa chỉ',
  searchNoResults: 'Không tìm thấy kết quả',
  searchError: 'Lỗi khi tìm kiếm',
  searchRetry: 'Thử lại',
  // Route booking modal
  bookingDiscountCode: 'Mã giảm giá',
  bookingPaymentCash: 'Tiền mặt',
  bookingBookButton: 'ĐẶT XE',
  // Home screen
  homeServicesTitle: 'Dịch vụ',
  homeServiceRide: 'Đặt xe',
  homeServiceDelivery: 'Giao hàng',
  homeServiceGrocery: 'Đi chợ',
  homeServiceFood: 'Đồ ăn',
  homeServiceParcel: 'Gửi hàng',
  homeServiceMore: 'Thêm',
  homeBannersTitle: 'Đặt ngay',
  homeNearbyTitle: 'Gần đây',
  // Search destination — pickup mode
  searchPickupLocation: 'Điểm đón của bạn',
  searchChangePickup: 'Thay đổi',
  // Bottom tabs
  tabHome: 'Trang chủ',
  tabExplore: 'Khám phá',
  tabProfile: 'Cá nhân',
  // Profile & settings
  profileTitle: 'Cá nhân',
  profileEdit: 'Sửa',
  profileSave: 'Lưu',
  profileCancel: 'Hủy',
  profileNameLabel: 'Tên hiển thị',
  profileNamePlaceholder: 'Nhập tên của bạn',
  profilePhoneLabel: 'Số điện thoại',
  profileEmailLabel: 'Email',
  profileSettingsTitle: 'Cài đặt',
  profileThemeLabel: 'Chế độ tối',
  profileThemeDark: 'Tối',
  profileThemeLight: 'Sáng',
  profileLanguageLabel: 'Ngôn ngữ',
  profileLogout: 'Đăng xuất',
  profileUpdateError: 'Không cập nhật được hồ sơ',
  // Active trip tracking
  tripFinding: 'Đang tìm tài xế',
  tripEnRoute: 'Tài xế đang đến',
  tripArrived: 'Tài xế đã đến điểm đón',
  tripInProgress: 'Đang trên đường đi',
  tripCompleted: 'Chuyến đi hoàn tất',
  tripFindingHint: 'Vui lòng chờ trong giây lát...',
  tripFare: 'Cước phí',
  tripCancel: 'Hủy chuyến',
  tripDone: 'Hoàn tất',
  // Driver dashboard
  dashboardOnline: 'Trực tuyến',
  dashboardOffline: 'Ngoại tuyến',
  dashboardGoOnline: 'Bắt đầu nhận cuốc',
  dashboardGoOffline: 'Dừng nhận cuốc',
  dashboardTripsToday: 'Cuốc hôm nay',
  dashboardWaitingForOffer: 'Đang chờ cuốc mới...',
}
export default vi;
