// Country display names (en + vi). Runtime-independent — avoids
// Intl.DisplayNames, which Hermes does not support without full-ICU.
// Originally generated from i18n-iso-countries (CLDR) intersected with
// libphonenumber-js supported regions, then hand-edited to short, common names.
//
// Naming convention (follow this when adding/editing entries):
//   1. Use the common short name, not the official long form
//      (e.g. "Laos" not "Lao People's Democratic Republic").
//   2. Drop institutional prefixes/suffixes: "Republic of", "Federated States
//      of", "Islamic Republic of", "State of", etc.
//   3. Drop political qualifiers and disputed parentheticals
//      (e.g. "Taiwan" not "Taiwan, Province of China"; "Falkland Islands" not
//      "Falkland Islands (Malvinas)"; no "(French part)"/"(Dutch part)").
//   4. Prefer the colloquial Vietnamese name where one is well established
//      (e.g. US → "Mỹ", GB → "Anh", KR → "Hàn Quốc"). Otherwise keep the
//      English name as-is for places without a common Vietnamese form.
//   5. Keep both `en` and `vi` filled; never leave a value equal to the raw
//      ISO2 code.
// When regenerating for a new locale, re-apply these manual short names.

// 2. VARIABLES & TYPES
export interface CountryNames {
  en: string;
  vi: string;
}

export const COUNTRY_NAMES: Record<string, CountryNames> = {
  AC: { en: "Ascension Island", vi: "Đảo Ascension" },
  AD: { en: "Andorra", vi: "Andorra" },
  AE: { en: "United Arab Emirates", vi: "Tiểu Vương Quốc Ả Rập" },
  AF: { en: "Afghanistan", vi: "Afghanistan" },
  AG: { en: "Antigua and Barbuda", vi: "Antigua và Barbuda" },
  AI: { en: "Anguilla", vi: "Anguilla" },
  AL: { en: "Albania", vi: "Albania" },
  AM: { en: "Armenia", vi: "Armenia" },
  AO: { en: "Angola", vi: "Angola" },
  AR: { en: "Argentina", vi: "Argentina" },
  AS: { en: "American Samoa", vi: "American Samoa" },
  AT: { en: "Austria", vi: "Austria" },
  AU: { en: "Australia", vi: "Úc" },
  AW: { en: "Aruba", vi: "Aruba" },
  AX: { en: "Åland Islands", vi: "Aland" },
  AZ: { en: "Azerbaijan", vi: "Azerbaijan" },
  BA: { en: "Bosnia and Herzegovina", vi: "Bosnia và Herzegovina" },
  BB: { en: "Barbados", vi: "Barbados" },
  BD: { en: "Bangladesh", vi: "Bangladesh" },
  BE: { en: "Belgium", vi: "Bỉ" },
  BF: { en: "Burkina Faso", vi: "Burkina Faso" },
  BG: { en: "Bulgaria", vi: "Bulgaria" },
  BH: { en: "Bahrain", vi: "Bahrain" },
  BI: { en: "Burundi", vi: "Burundi" },
  BJ: { en: "Benin", vi: "Benin" },
  BL: { en: "Saint Barthélemy", vi: "Saint Barthélemy" },
  BM: { en: "Bermuda", vi: "Bermuda" },
  BN: { en: "Brunei", vi: "Brunei" },
  BO: { en: "Bolivia", vi: "Bolivia" },
  BQ: { en: "Caribbean Netherlands", vi: "Caribe Hà Lan" },
  BR: { en: "Brazil", vi: "Brazil" },
  BS: { en: "Bahamas", vi: "Bahamas" },
  BT: { en: "Bhutan", vi: "Bhutan" },
  BW: { en: "Botswana", vi: "Botswana" },
  BY: { en: "Belarus", vi: "Belarus" },
  BZ: { en: "Belize", vi: "Belize" },
  CA: { en: "Canada", vi: "Canada" },
  CC: { en: "Cocos Islands", vi: "Cocos" },
  CD: { en: "DR Congo", vi: "CHDC Congo" },
  CF: { en: "Central African Republic", vi: "Cộng hòa Trung Phi" },
  CG: { en: "Congo", vi: "Congo" },
  CH: { en: "Switzerland", vi: "Thụy Sĩ" },
  CI: { en: "Cote d'Ivoire", vi: "Cote d'Ivoire" },
  CK: { en: "Cook Islands", vi: "Cook" },
  CL: { en: "Chile", vi: "Chile" },
  CM: { en: "Cameroon", vi: "Cameroon" },
  CN: { en: "China", vi: "Trung Quốc" },
  CO: { en: "Colombia", vi: "Colombia" },
  CR: { en: "Costa Rica", vi: "Costa Rica" },
  CU: { en: "Cuba", vi: "Cuba" },
  CV: { en: "Cape Verde", vi: "Cape Verde" },
  CW: { en: "Curaçao", vi: "Curaçao" },
  CX: { en: "Christmas Island", vi: "Đảo Giáng sinh" },
  CY: { en: "Cyprus", vi: "Cyprus" },
  CZ: { en: "Czechia", vi: "Séc" },
  DE: { en: "Germany", vi: "Đức" },
  DJ: { en: "Djibouti", vi: "Djibouti" },
  DK: { en: "Denmark", vi: "Đan Mạch" },
  DM: { en: "Dominica", vi: "Dominica" },
  DO: { en: "Dominican Republic", vi: "Cộng hòa Dominica" },
  DZ: { en: "Algeria", vi: "Algeria" },
  EC: { en: "Ecuador", vi: "Ecuador" },
  EE: { en: "Estonia", vi: "Estonia" },
  EG: { en: "Egypt", vi: "Ai Cập" },
  EH: { en: "Western Sahara", vi: "Tây Sahara" },
  ER: { en: "Eritrea", vi: "Eritrea" },
  ES: { en: "Spain", vi: "Tây Ban Nha" },
  ET: { en: "Ethiopia", vi: "Ethiopia" },
  FI: { en: "Finland", vi: "Phần Lan" },
  FJ: { en: "Fiji", vi: "Fiji" },
  FK: { en: "Falkland Islands", vi: "Falkland" },
  FM: { en: "Micronesia", vi: "Micronesia" },
  FO: { en: "Faroe Islands", vi: "Faroe" },
  FR: { en: "France", vi: "Pháp" },
  GA: { en: "Gabon", vi: "Gabon" },
  GB: { en: "United Kingdom", vi: "Anh" },
  GD: { en: "Grenada", vi: "Grenada" },
  GE: { en: "Georgia", vi: "Georgia" },
  GF: { en: "French Guiana", vi: "Guyane thuộc Pháp" },
  GG: { en: "Guernsey", vi: "Guernsey" },
  GH: { en: "Ghana", vi: "Ghana" },
  GI: { en: "Gibraltar", vi: "Gibraltar" },
  GL: { en: "Greenland", vi: "Greenland" },
  GM: { en: "Gambia", vi: "Gambia" },
  GN: { en: "Guinea", vi: "Guinea" },
  GP: { en: "Guadeloupe", vi: "Guadeloupe" },
  GQ: { en: "Equatorial Guinea", vi: "Guinea Xích Đạo" },
  GR: { en: "Greece", vi: "Hy Lạp" },
  GT: { en: "Guatemala", vi: "Guatemala" },
  GU: { en: "Guam", vi: "Guam" },
  GW: { en: "Guinea-Bissau", vi: "Guinea-Bissau" },
  GY: { en: "Guyana", vi: "Guyana" },
  HK: { en: "Hong Kong", vi: "Hồng Kông" },
  HN: { en: "Honduras", vi: "Honduras" },
  HR: { en: "Croatia", vi: "Croatia" },
  HT: { en: "Haiti", vi: "Haiti" },
  HU: { en: "Hungary", vi: "Hungary" },
  ID: { en: "Indonesia", vi: "Indonesia" },
  IE: { en: "Ireland", vi: "Ireland" },
  IL: { en: "Israel", vi: "Israel" },
  IM: { en: "Isle of Man", vi: "Đảo Man" },
  IN: { en: "India", vi: "Ấn Độ" },
  IO: { en: "British Indian Ocean Territory", vi: "Lãnh thổ Ấn Độ Dương thuộc Anh" },
  IQ: { en: "Iraq", vi: "Iraq" },
  IR: { en: "Iran", vi: "Iran" },
  IS: { en: "Iceland", vi: "Iceland" },
  IT: { en: "Italy", vi: "Ý" },
  JE: { en: "Jersey", vi: "Jersey" },
  JM: { en: "Jamaica", vi: "Jamaica" },
  JO: { en: "Jordan", vi: "Jordan" },
  JP: { en: "Japan", vi: "Nhật Bản" },
  KE: { en: "Kenya", vi: "Kenya" },
  KG: { en: "Kyrgyzstan", vi: "Kyrgyzstan" },
  KH: { en: "Cambodia", vi: "Campuchia" },
  KI: { en: "Kiribati", vi: "Kiribati" },
  KM: { en: "Comoros", vi: "Comoros" },
  KN: { en: "Saint Kitts and Nevis", vi: "Saint Kitts và Nevis" },
  KP: { en: "North Korea", vi: "Triều Tiên" },
  KR: { en: "South Korea", vi: "Hàn Quốc" },
  KW: { en: "Kuwait", vi: "Cô-oét" },
  KY: { en: "Cayman Islands", vi: "Cayman" },
  KZ: { en: "Kazakhstan", vi: "Kazakhstan" },
  LA: { en: "Laos", vi: "Lào" },
  LB: { en: "Lebanon", vi: "Lebanon" },
  LC: { en: "Saint Lucia", vi: "Saint Lucia" },
  LI: { en: "Liechtenstein", vi: "Liechtenstein" },
  LK: { en: "Sri Lanka", vi: "Sri Lanka" },
  LR: { en: "Liberia", vi: "Liberia" },
  LS: { en: "Lesotho", vi: "Lesotho" },
  LT: { en: "Lithuania", vi: "Lithuania" },
  LU: { en: "Luxembourg", vi: "Luxembourg" },
  LV: { en: "Latvia", vi: "Latvia" },
  LY: { en: "Libya", vi: "Libya" },
  MA: { en: "Morocco", vi: "Ma-rốc" },
  MC: { en: "Monaco", vi: "Monaco" },
  MD: { en: "Moldova", vi: "Moldova" },
  ME: { en: "Montenegro", vi: "Montenegro" },
  MF: { en: "Saint Martin", vi: "Saint Martin" },
  MG: { en: "Madagascar", vi: "Madagascar" },
  MH: { en: "Marshall Islands", vi: "Marshall" },
  MK: { en: "North Macedonia", vi: "Bắc Macedonia" },
  ML: { en: "Mali", vi: "Mali" },
  MM: { en: "Myanmar", vi: "Myanmar" },
  MN: { en: "Mongolia", vi: "Mông Cổ" },
  MO: { en: "Macao", vi: "Ma Cao" },
  MP: { en: "Northern Mariana Islands", vi: "Bắc Mariana" },
  MQ: { en: "Martinique", vi: "Martinique" },
  MR: { en: "Mauritania", vi: "Mauritania" },
  MS: { en: "Montserrat", vi: "Montserrat" },
  MT: { en: "Malta", vi: "Malta" },
  MU: { en: "Mauritius", vi: "Mauritius" },
  MV: { en: "Maldives", vi: "Maldives" },
  MW: { en: "Malawi", vi: "Malawi" },
  MX: { en: "Mexico", vi: "Mexico" },
  MY: { en: "Malaysia", vi: "Malaysia" },
  MZ: { en: "Mozambique", vi: "Mozambique" },
  NA: { en: "Namibia", vi: "Namibia" },
  NC: { en: "New Caledonia", vi: "New Caledonia" },
  NE: { en: "Niger", vi: "Niger" },
  NF: { en: "Norfolk Island", vi: "Đảo Norfolk" },
  NG: { en: "Nigeria", vi: "Nigeria" },
  NI: { en: "Nicaragua", vi: "Nicaragua" },
  NL: { en: "Netherlands", vi: "Hà Lan" },
  NO: { en: "Norway", vi: "Na Uy" },
  NP: { en: "Nepal", vi: "Nepal" },
  NR: { en: "Nauru", vi: "Nauru" },
  NU: { en: "Niue", vi: "Niue" },
  NZ: { en: "New Zealand", vi: "New Zealand" },
  OM: { en: "Oman", vi: "Oman" },
  PA: { en: "Panama", vi: "Panama" },
  PE: { en: "Peru", vi: "Peru" },
  PF: { en: "French Polynesia", vi: "Polynésie thuộc Pháp" },
  PG: { en: "Papua New Guinea", vi: "Papua New Guinea" },
  PH: { en: "Philippines", vi: "Philippines" },
  PK: { en: "Pakistan", vi: "Pakistan" },
  PL: { en: "Poland", vi: "Ba Lan" },
  PM: { en: "Saint Pierre and Miquelon", vi: "Saint Pierre và Miquelon" },
  PR: { en: "Puerto Rico", vi: "Puerto Rico" },
  PS: { en: "Palestine", vi: "Palestine" },
  PT: { en: "Portugal", vi: "Bồ Đào Nha" },
  PW: { en: "Palau", vi: "Palau" },
  PY: { en: "Paraguay", vi: "Paraguay" },
  QA: { en: "Qatar", vi: "Qatar" },
  RE: { en: "Reunion", vi: "Reunion" },
  RO: { en: "Romania", vi: "Rumani" },
  RS: { en: "Serbia", vi: "Serbia" },
  RU: { en: "Russia", vi: "Nga" },
  RW: { en: "Rwanda", vi: "Rwanda" },
  SA: { en: "Saudi Arabia", vi: "Saudi Arabia" },
  SB: { en: "Solomon Islands", vi: "Solomon" },
  SC: { en: "Seychelles", vi: "Seychelles" },
  SD: { en: "Sudan", vi: "Sudan" },
  SE: { en: "Sweden", vi: "Thụy Điển" },
  SG: { en: "Singapore", vi: "Singapore" },
  SH: { en: "Saint Helena", vi: "Saint Helena" },
  SI: { en: "Slovenia", vi: "Slovenia" },
  SJ: { en: "Svalbard and Jan Mayen", vi: "Svalbard và Jan Mayen" },
  SK: { en: "Slovakia", vi: "Slovakia" },
  SL: { en: "Sierra Leone", vi: "Sierra Leone" },
  SM: { en: "San Marino", vi: "San Marino" },
  SN: { en: "Senegal", vi: "Senegal" },
  SO: { en: "Somalia", vi: "Somalia" },
  SR: { en: "Suriname", vi: "Suriname" },
  SS: { en: "South Sudan", vi: "Nam Sudan" },
  ST: { en: "Sao Tome and Principe", vi: "Sao Tome và Principe" },
  SV: { en: "El Salvador", vi: "El Salvador" },
  SX: { en: "Sint Maarten", vi: "Sint Maarten" },
  SY: { en: "Syria", vi: "Syria" },
  SZ: { en: "Eswatini", vi: "Eswatini" },
  TA: { en: "Tristan da Cunha", vi: "Tristan da Cunha" },
  TC: { en: "Turks and Caicos Islands", vi: "Turks và Caicos" },
  TD: { en: "Chad", vi: "Chad" },
  TG: { en: "Togo", vi: "Togo" },
  TH: { en: "Thailand", vi: "Thái Lan" },
  TJ: { en: "Tajikistan", vi: "Tajikistan" },
  TK: { en: "Tokelau", vi: "Tokelau" },
  TL: { en: "Timor-Leste", vi: "Timor-Leste" },
  TM: { en: "Turkmenistan", vi: "Turkmenistan" },
  TN: { en: "Tunisia", vi: "Tunisia" },
  TO: { en: "Tonga", vi: "Tonga" },
  TR: { en: "Türkiye", vi: "Thổ Nhĩ Kỳ" },
  TT: { en: "Trinidad and Tobago", vi: "Trinidad và Tobago" },
  TV: { en: "Tuvalu", vi: "Tuvalu" },
  TW: { en: "Taiwan", vi: "Đài Loan" },
  TZ: { en: "Tanzania", vi: "Tanzania" },
  UA: { en: "Ukraine", vi: "Ukraine" },
  UG: { en: "Uganda", vi: "Uganda" },
  US: { en: "United States", vi: "Mỹ" },
  UY: { en: "Uruguay", vi: "Uruguay" },
  UZ: { en: "Uzbekistan", vi: "Uzbekistan" },
  VA: { en: "Vatican", vi: "Vatican" },
  VC: { en: "Saint Vincent and the Grenadines", vi: "Saint Vincent và Grenadines" },
  VE: { en: "Venezuela", vi: "Venezuela" },
  VG: { en: "British Virgin Islands", vi: "Virgin thuộc Anh" },
  VI: { en: "U.S. Virgin Islands", vi: "Virgin thuộc Mỹ" },
  VN: { en: "Vietnam", vi: "Việt Nam" },
  VU: { en: "Vanuatu", vi: "Vanuatu" },
  WF: { en: "Wallis and Futuna", vi: "Wallis và Futuna" },
  WS: { en: "Samoa", vi: "Samoa" },
  XK: { en: "Kosovo", vi: "Kosovo" },
  YE: { en: "Yemen", vi: "Yemen" },
  YT: { en: "Mayotte", vi: "Mayotte" },
  ZA: { en: "South Africa", vi: "Nam Phi" },
  ZM: { en: "Zambia", vi: "Zambia" },
  ZW: { en: "Zimbabwe", vi: "Zimbabwe" },
};
