-- AlterEnum
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'LOOKING_DRIVER';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'NO_DRIVER';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'DRIVER_ARRIVED';
